'use client';
import {useEffect,useState} from 'react';
import {bookingRequest,pagesDemo} from '@/lib/booking-client';
import {ArrowRight,ArrowLeft,CarFront,CalendarDays,Clock3,Sun,Navigation,Check,ShieldCheck,MapPin,Route,History,CircleGauge,Info} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {bookingSchema,BookingInput,Booking,modes,estimate} from '@/lib/booking';
const fresh=():BookingInput=>({id:crypto.randomUUID(),mode:'now',pickup:'',destination:'',start:'',hours:3,car:'',transmission:'automatic',name:'',phone:'',notes:''});
const labels={now:'Leave when you’re ready',scheduled:'Plan your next trip',hourly:'A driver, on your time',day:'Keep the whole day open'};
const icons={now:Navigation,scheduled:CalendarDays,hourly:Clock3,day:Sun};
function when(b:BookingInput){return b.mode==='now'?'As soon as possible':new Date(b.start).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});}
const money=(v:number)=>'₹'+v.toLocaleString('en-IN');
export default function BookingApp(){
 const [form,setForm]=useState<BookingInput>({id:'',mode:'now',pickup:'',destination:'',start:'',hours:3,car:'',transmission:'automatic',name:'',phone:'',notes:''});
 const [tab,setTab]=useState('book'),[step,setStep]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false),[items,setItems]=useState<Booking[]>([]),[loading,setLoading]=useState(false),[historyError,setHistoryError]=useState(''),[saved,setSaved]=useState<Booking|null>(null),[cancel,setCancel]=useState<string|null>(null);
 useEffect(()=>{setForm(f=>({...f,id:crypto.randomUUID()}));},[]);
 function update(k:keyof BookingInput,v:any){setForm(f=>({...f,[k]:v}));setError('');}
 async function load(){setLoading(true);setHistoryError('');try{const r=await bookingRequest('/api/bookings');const j:any=await r.json();if(!r.ok)throw Error(j.error);setItems(j.bookings);}catch(e){setHistoryError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(tab==='history')void load();},[tab]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'open_booking_history',description:'Open booking history and load saved demo bookings. Does not create or cancel bookings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||Object.keys(input).length)throw Error('No parameters accepted');setTab('history');await load();return {view:'history'};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 function review(e:React.FormEvent){e.preventDefault();const checked=bookingSchema.safeParse(form);if(!checked.success){setError(checked.error.issues[0].message);return;}setForm(checked.data);setStep(2);setError('');window.scrollTo({top:0,behavior:'smooth'});}
 async function save(){setBusy(true);setError('');try{const r=await bookingRequest('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j:any=await r.json();if(!r.ok)throw Error(j.error);setSaved(j.booking);setStep(3);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function cancelBooking(id:string){setBusy(true);setHistoryError('');try{const r=await bookingRequest('/api/bookings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const j:any=await r.json();if(!r.ok)throw Error(j.error);setItems(xs=>xs.map(x=>x.id===id?{...x,status:'cancelled'}:x));}catch(e){setHistoryError((e as Error).message);}finally{setBusy(false);setCancel(null);}}
 function reset(){setForm(fresh());setSaved(null);setStep(1);setError('');setTab('book');}
 const duration=form.mode==='day'?'8 hours':form.mode==='hourly'?`${form.hours} hours`:'One-way trip';
 function summary(b:BookingInput){return <div className="summary"><div className="route-line"><span className="dot"/><div><small>PICKUP</small><strong>{b.pickup}</strong></div></div><div className="route-line"><MapPin size={17}/><div><small>DESTINATION</small><strong>{b.destination}</strong></div></div><div className="facts"><span><CalendarDays/>{when(b)}</span><span><CarFront/>{b.car} · {b.transmission}</span><span><Clock3/>{b.mode==='day'?'8 hours':b.mode==='hourly'?b.hours+' hours':'One-way trip'}</span></div></div>;}
 return <div className="shell"><Tabs value={tab} onValueChange={setTab}>
 <header><button className="brand" onClick={()=>setTab('book')} aria-label="Takewheel home"><span className="brand-icon"><CircleGauge/></span>takewheel<span className="brand-dot">.</span></button><TabsList className="main-nav"><TabsTrigger value="book"><CarFront/>Book a driver</TabsTrigger><TabsTrigger value="history"><History/>My bookings</TabsTrigger></TabsList><span className="preview-badge"><span/> DEMO APP</span></header>
 <div className="demo-strip"><Info size={15}/><span>{pagesDemo?'Browser-only demo. Bookings stay on this device. Use sample contact details. No driver or payment.':'Try a booking. No real driver is dispatched and no payment is taken.'}</span></div>
 <TabsContent value="book"><main><div className="intro"><span className="eyebrow">YOUR CAR. YOUR WAY HOME.</span><h1>Let someone else<br className="mobile-break"/> take the wheel<span>.</span></h1><p>A driver for your own car, whenever you need a break.</p></div>
 <div className="workspace"><section className="booking-panel"><div className="steps">{['Trip details','Review','Saved'].map((x,i)=><span key={x} className={step>=i+1?'active':''}><b>{step>i+1?<Check size={12}/>:i+1}</b>{x}</span>)}</div>
 {step===1&&<form onSubmit={review}><div className="section-top"><h2>Book your driver</h2><span>01 / 03</span></div><RadioGroup className="mode-grid" value={form.mode} onValueChange={v=>update('mode',v)} aria-label="Hire type">{Object.entries(modes).map(([key,label])=>{const Icon=icons[key as keyof typeof icons];return <label key={key} className={'mode '+(form.mode===key?'selected':'')}><RadioGroupItem className="mode-radio" value={key}/><Icon/><strong>{label}</strong></label>;})}</RadioGroup><p className="mode-description">{labels[form.mode]}{form.mode==='day'?' · 8-hour hire':''}</p>
 <div className="address-fields"><label><span><span className="dot"/>Pickup location</span><input required minLength={5} maxLength={250} placeholder="Full address, area and city" value={form.pickup} onChange={e=>update('pickup',e.target.value)} autoComplete="street-address"/></label><label><span><MapPin size={15}/>Destination</span><input required minLength={5} maxLength={250} placeholder={form.mode==='hourly'||form.mode==='day'?'Final drop-off address, area and city':'Where should we take you and your car?'} value={form.destination} onChange={e=>update('destination',e.target.value)}/></label></div><p className="field-help">Enter exact addresses. Live maps and address suggestions aren’t connected.</p>
 {form.mode!=='now'&&<div className="two-col"><label>Start date & time<input type="datetime-local" required value={form.start?localDate(form.start):''} onChange={e=>update('start',e.target.value?new Date(e.target.value).toISOString():'')}/><small>In your device’s local time</small></label>{form.mode==='hourly'&&<label>Number of hours<input type="number" min="2" max="12" required value={form.hours} onChange={e=>update('hours',Number(e.target.value))}/><small>2–12 hours</small></label>}</div>}
 <div className="divider"/><h3>Your car</h3><label>Make & model<input required minLength={2} maxLength={80} placeholder="e.g. Hyundai i20" value={form.car} onChange={e=>update('car',e.target.value)}/></label><RadioGroup className="transmission" value={form.transmission} onValueChange={v=>update('transmission',v)} aria-label="Transmission"><label><RadioGroupItem value="automatic"/>Automatic</label><label><RadioGroupItem value="manual"/>Manual</label></RadioGroup>
 <div className="two-col"><label>Your name<input required minLength={2} maxLength={80} autoComplete="name" placeholder="Full name" value={form.name} onChange={e=>update('name',e.target.value)}/></label><label>Contact number<input type="tel" required autoComplete="tel" placeholder="+91 98765 43210" value={form.phone} onChange={e=>update('phone',e.target.value)}/></label></div><label>Pickup instructions <span className="optional">Optional</span><textarea maxLength={500} rows={2} placeholder="Parking level, gate number or meeting point" value={form.notes} onChange={e=>update('notes',e.target.value)}/></label>
 {error&&<p className="error" role="alert">{error}</p>}<div className="form-bottom"><div><small>ILLUSTRATIVE ESTIMATE</small><strong>{money(estimate(form))}<span> / {form.mode==='day'?'8 hours':form.mode==='hourly'?`${form.hours} hours`:'trip'}</span></strong></div><button className="primary" type="submit">Review booking<ArrowRight size={18}/></button></div></form>}
 {step===2&&<div className="review"><button className="back" onClick={()=>setStep(1)}><ArrowLeft size={16}/>Edit details</button><h2>Everything look right?</h2><p className="muted">Review your trip before saving a demo booking.</p><span className="pill">{modes[form.mode]} · {duration}</span>{summary(form)}<div className="contact-review"><strong>{form.name}</strong><span>{form.phone}</span>{form.notes&&<p>{form.notes}</p>}</div><div className="price-row"><span>Illustrative estimate</span><strong>{money(estimate(form))}</strong></div><p className="field-help">Sample pricing only. Route distance, tolls, parking and real availability are not calculated. Nothing will be charged.</p><div className="notice"><ShieldCheck/><p><strong>This saves a demo booking only.</strong><br/>No driver will arrive. Please arrange another way home if you need a ride now.</p></div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" onClick={save} disabled={busy}>{busy?'Saving…':'Save demo booking'}<ArrowRight size={18}/></button></div>}
 {step===3&&saved&&<div className="confirmation"><span className="success-icon"><Check size={30}/></span><span className="eyebrow">DEMO BOOKING SAVED</span><h2>Your trip is on the list.</h2><p>{pagesDemo?'Saved in this browser only.':'Saved to your account.'} <strong>No driver has been assigned.</strong></p><span className="reference">#{saved.id.slice(0,8).toUpperCase()}</span>{summary(saved)}<div className="notice"><Info/><p>This is a test booking, not a confirmed ride. No payment was taken.</p></div><button className="primary full" onClick={()=>setTab('history')}>View my bookings<ArrowRight size={18}/></button><button className="back" onClick={reset}>Book another trip</button></div>}
 </section><aside><div className="journey-card"><span className="eyebrow">A LITTLE PEACE OF MIND</span><h2>You relax.<br/>Your car comes too.</h2><div className="road-art" aria-hidden="true"><div className="road"><span/><span/><span/></div><span className="start-marker"/><div className="car-art"><CarFront size={72} strokeWidth={1.2}/></div><span className="end-marker"><MapPin size={21}/></span></div><div className="journey-caption"><span>YOU + YOUR CAR</span><ArrowRight size={20}/><span>HOME</span></div></div><div className="aside-note"><CircleGauge/><div><h3>Your car, a helping hand</h3><p>After a long journey, a late evening, or when you’re not feeling up to driving.</p></div></div><div className="pricing-note"><span className="eyebrow">SIMPLE DEMO PRICING</span><div><span>One-way trip</span><strong>₹450</strong></div><div><span>Hourly · minimum 2 hours</span><strong>₹250 / hr</strong></div><div><span>Full day · 8 hours</span><strong>₹1,800</strong></div><p>Illustrative amounts, not live quotes.</p></div></aside></div></main></TabsContent>
 <TabsContent value="history"><main><div className="history-title"><div><span className="eyebrow">YOUR TRIPS, ALL TOGETHER</span><h1>My bookings<span>.</span></h1><p className="muted">{pagesDemo?'Saved only in this browser. Clearing site data removes your history.':'Demo bookings are saved to your signed-in account.'}</p></div><button className="primary" onClick={reset}>New booking<ArrowRight size={17}/></button></div>{loading?<div className="empty">Loading your bookings…</div>:historyError?<div className="empty"><p className="error" role="alert">{historyError}</p><button className="secondary" onClick={load}>Retry</button>{historyError.includes('sign in')&&<a className="primary" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>}</div>:items.length===0?<div className="empty"><Route size={42}/><h2>Your next trip starts here.</h2><p>No bookings yet. Try saving your first demo trip.</p><button className="primary" onClick={reset}>Book a driver<ArrowRight size={17}/></button></div>:<div className="history-grid">{items.map(b=><article className="history-card" key={b.id}><div className="card-top"><span className={'pill '+(b.status==='cancelled'?'cancelled':'')}>{b.status==='cancelled'?'Cancelled':'Demo saved'}</span><small>#{b.id.slice(0,8).toUpperCase()}</small></div><h2>{modes[b.mode]}</h2>{summary(b)}<div className="history-details"><span>{b.name} · {b.phone}</span>{b.notes&&<p>{b.notes}</p>}</div><div className="card-bottom"><div><small>ILLUSTRATIVE ESTIMATE</small><strong>{money(estimate(b))}</strong></div>{b.status!=='cancelled'&&<button className="back" disabled={busy} onClick={()=>setCancel(b.id)}>Cancel booking</button>}</div><p className="field-help">{b.status==='cancelled'?'Cancelled demo booking. No charge.':'No driver assigned. No payment taken.'}</p></article>)}</div>}</main></TabsContent>
 <footer><span>takewheel.</span><p>A driver for your own car.</p><span>DEMO · NOT A LIVE TRANSPORT SERVICE</span></footer></Tabs>
 <AlertDialog open={!!cancel} onOpenChange={v=>{if(!v)setCancel(null)}}><AlertDialogContent><AlertDialogTitle>Cancel this demo booking?</AlertDialogTitle><AlertDialogDescription>It will stay in your booking history as cancelled. There is no cancellation charge.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep booking</AlertDialogCancel><AlertDialogAction onClick={()=>{if(cancel)void cancelBooking(cancel)}}>Cancel booking</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
function localDate(iso:string){const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}



